// Promise.resolve(1)
//   .then((res) => {
//     console.log(res)
//   })
//   .catch((err) => {
//     console.log(8989);
//     return 3
//   })
//   .then((res) => {
//     console.log(res)
//   })

